# Generated by Django 2.2.7 on 2019-12-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('picture', models.CharField(max_length=1000)),
                ('bio', models.TextField(verbose_name='About yourself')),
                ('website', models.URLField(blank=True, null=True)),
                ('phonenumber', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
